### ISSUE TITLE
Progress bar on DarkTheme

### ISSUE THREAD

**Issue by leoheck** [obelisk79/OpenTheme#136]
Hi @obelisk79 , I have a script that creates a progress bar.

But the colors do not look right on dark theme.

See, the 0%
![image](https://github.com/user-attachments/assets/3f5e7aa9-9a53-4383-9476-ec0c229ce757)

and the 100% look the same.
![image](https://github.com/user-attachments/assets/7786012e-964a-44ee-9a5b-593bb14d0aad)

So, no progress is indicated through the colors.. just the number changes.

Is this something that can be tweaked with the OpenTheme?

**Comment by obelisk79** [comment]
I'd this an issue exclusive to open theme? It just all dark themes?

**Comment by leoheck** [comment]
OpenLight theme has the same issue.
![image](https://github.com/user-attachments/assets/8daa76d6-af80-44a6-ba33-4c0b99f72a59)

Classic Light has this just fine.
![image](https://github.com/user-attachments/assets/66d0089e-cd1d-4be4-8fd3-d997f2917c0c)
![image](https://github.com/user-attachments/assets/6a5c2634-1060-4a8b-b147-a0daefd0e449)

My guess is that the 0% or default background is wrong somewhere.

This is the my current OpenTheme version
```
commit 80399168ab27c660a9a14812b67492f412f3148f (HEAD -> main, origin/main, origin/HEAD)
Merge: 81cd43a 01cb44a
Author: obelisk79 <obelisk79@gmail.com>
Date:   Fri Sep 13 17:58:50 2024 -0400

    Merge pull request #127 from obelisk79/qplaintextedit
    
    Correct undefined style for QPlainTextEdit
```

**Comment by leoheck** [comment]
A progress bar like that can be found on Asm4 WB 

This icon here ![image](https://github.com/user-attachments/assets/1f6b77be-af91-44be-a5de-245553e58c95)
You just have to crate an Assembly (Part-like icon on Asm4 WB) and you will be able to launch the tool

**Comment by leoheck** [comment]
Ah, there is another progress bar easy to find.

When loading a big FCStd, it takes time to load and this issue can be seen in the bottom right corner.
The bar has always the same color.

![image](https://github.com/user-attachments/assets/4967922e-3bdd-46b3-931f-a5d17cc2d526)

**Comment by leoheck** [comment]
https://doc.qt.io/qt-6/stylesheet-examples.html#customizing-qprogressbar

**Comment by leoheck** [comment]
I could fix it with this:

![image](https://github.com/user-attachments/assets/97a1f814-706a-4b4a-951b-c8bbdc8c3286)

```css
QProgressBar,
QProgressBar:horizontal {
    color: $primaryText;
    min-height: 24px;
    // background-color: transparent;
    text-align: center;
    // border: 1px solid $contrastBorder;
    // &::chunk {
        // background-color: $accentBorder;
    // }
}

QProgressBar {
    background-color: $primaryBackground;
    border: 1px solid $contrastBorder;
}

QProgressBar::chunk {
    background-color: $accentBackground;
}
```
